spring.application.name=ristorino-backend
server.servlet.context-path=/api/v1
server.port=8085
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ristorino;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Password123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
api.key=AIzaSyDHtxUFhHgkOObqnkq-F_AQwQo7lRuRCDA